### ISSUE TITLE
"thanks" for ignoring GNU/Linux

### ISSUE THREAD

**Issue by nitrofurano** [rsms/interface#9]
at readme.md we see "Follow the instructions in "install-mac.txt" or "install-win.txt", depending on what operating system you're using." - where is GNU/Linux?

and btw, "mac" is the hardware, not the operating system (for example, now i'm running Ubuntu on a Mac! :D )

another thing is why are people calling "win" a so crappy operating system... wouldn't it make more sense calling it as "lose"?

**Comment by meyer** [comment]
omg

**Comment by fitojb** [comment]
Who cares… This is not even a creative face—it’s just a half-done interpolation of San Francisco plus Roboto.

**Comment by meyer** [comment]
@fitojb before you completely dismiss Interface, you should know that San Francisco’s just a “knockoff” of [Neutral Sans](https://www.typotheque.com/blog/neutral), which in turn is just an amalgamation of many sources (most notably DIN 1451).

**Comment by rsms** [comment]
@nitrofurano I don't use Linux with a desktop, so I'm not personally familiar with how fonts are managed or installed on various Linux distributions (and same goes for BSD et al.) If you feel strongly about this, I propose you submit a pull request with a "install-linux.txt" (and other platforms too if you want) that describes how to install the font files.

@fitojb Please behave. I would normally remove a comment like yours, but since @meyer's reply is pretty funny, I'll leave it here for future generations, who will hopefully get a laugh out of it. In all seriousness, please respect https://github.com/rsms/interface/blob/master/CODE_OF_CONDUCT.md and each other :)

**Comment by nitrofurano** [comment]
i said GNU/Linux - Linux is just the kernel, also used in Android! :D 

on the user side, fonts there can be easily installed merely by copying them to "~/.fonts/" - for all users, perhaps "/usr/share/fonts/" needs some researching on how to organize them as family (like "/usr/share/fonts/truetype/interface/") - i guess it might be helpful

and as soon as the oblique typefaces will get their misspelled name fixed (they are not italics), for sure it will be a pleasure submitting a pull request! ;p

**Comment by marsjaninzmarsa** [comment]
1. Can't find `install-mac.txt` and `install-win.txt` in repository, only in release archive, so targeting pull request could be tricky.
2. Issue is still the issue, may you please reopen it (maybe after changing title to something little more appropriate)?
